name: Poc

env:
  SERVICE_PREFIX: api-v2

on:
  workflow_dispatch:
    inputs:
      service-name:
        type: choice
        description: Select service to deploy
        options:
          - service-a
          - service-b
jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: ${{ github.event.inputs.service-name }}
            service: ${{ env.SERVICE_PREFIX }}-${{ github.event.inputs.service-name }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Build ${{ matrix.name }} start to deploy service > ${{ matrix.service }}"