name: Poc

env:
  SERVICE_NAME: api-v2-${{ github.event.inputs.service-name }}

on:
  workflow_dispatch:
    inputs:
      service-name:
        type: choice
        description: Select service to deploy
        options:
          - service-a
          - service-b
jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: ${{ github.event.inputs.service-name }}
            service: $SERVICE_PREFIX-${{ github.event.inputs.service-name }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Build ${{ matrix.name }} start to deploy service > ${{ matrix.service }}"
      - name: Manifest
        run: echo "Build ${{ matrix.name }} start to deploy service > ${{ matrix.service }}"
  eric:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: ${{ github.event.inputs.service-name }}
            service: $SERVICE_NAME

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: action/checkout@v3
        run: echo "Checking out branch ${{ env.GITHUB_WORKSPACE }}"
      - name: Deploy
        run: echo "Build service ${{ matrix.name }} start to deploy service > ${{ matrix.service }}"
      - name: Manifest
        run: echo "Build ${{ matrix.name }} start to deploy service > ${{ matrix.service }}"